### ISSUE TITLE
获取用户被点赞数量 有哪个API哇~~求分析。。

### ISSUE THREAD

**Issue by zzz6519003** [shanelau/zhihu#2]

**Comment by wittyfilter** [comment]
我也想知道！

**Comment by shanelau** [comment]
@zzz6519003  这个需要统计用户的所有回答，所有回到出来了，点赞评论等信息就出来了

**Comment by nnabuuu** [comment]
这反正是用cheerio做解析在User.js里面继续抓$('.zm-profile-header-user-agree')就好啦-。-

**Comment by zzz6519003** [comment]
我记得木有 profile card 里木有 点赞的信息

**Comment by wild-flame** [comment]
没那么麻烦，不用统计用户的所有回答的。

`<span class="zm-profile-header-user-agree"><span class="zm-profile-header-icon"></span><strong>168415</strong>赞同</span>`

在用户的主页里有，直接用cheerio里面做解析就好了。
