### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by shiya** [shanelau/zhihu#21]
没有license.md，readme里写欢迎贡献代码，但是代码里又有Copyright (c) 2014 Meizu bigertech, All rights reserved.
这个项目到底是不是开源的？

**Comment by shanelau** [comment]
已经添加 [MIT license](https://github.com/shanelau/zhihu/blob/master/LICENSE)
谢谢支持

**Comment by shanelau** [comment]
对于这个库 有什么新需求吗
