### ISSUE TITLE
知乎专栏 RSS

### ISSUE THREAD

**Issue by shanelau** [shanelau/zhihu#23]
为专栏提供一个 rss 订阅地址。 
官方目前没有提供。不知道未来有没有打算。

提供一个平台，存储专栏信息，然后输出该专栏的 rss 接口

**Comment by isnofate** [comment]
https://zhuanlan.zhihu.com/api/columns/bigertech/posts  浏览器访问正常，但 RSS 工具订阅报错，这是为啥呢？

RSS 工具：reeder，feedbin

**Comment by shanelau** [comment]
@isnofate 你发的这个 url 吗？ 这个不是 rss 的格式
