### ISSUE TITLE
正文中的标签没有被渲染

### ISSUE THREAD

**Issue by wizos** [shanelau/zhihu#24]
用 Inoreader 订阅后，正文中含有标签

**Comment by shanelau** [comment]
用的哪个一个功能。贴一下代码和结果

**Comment by wizos** [comment]
知乎收藏夹：http://xia.bigertech.com/rss/collection/2a62927d-a94c-4812-b45d-39fbb1ed0d18
![image](http://wizos.me/rss/QQ%E6%88%AA%E5%9B%BE20160901223432.png)

**Comment by shanelau** [comment]
这里得用富文本，不然格式太乱 没法看的。

这个 rss 做得很粗糙 ，不好用呢。 只做了一个版本

**Comment by wizos** [comment]
呃，有点不懂哈。
* 不用富文本不行么，不知道到格式乱在哪……不能过滤么？
