### ISSUE TITLE
QuestionAnswerListV2

### ISSUE THREAD

**Issue by 1736103466** [shanelau/zhihu#25]
Question.js下QuestionAnswerListV2请求 offset参数给的值是10，

  var opt = {
    uri: 'https://www.zhihu.com/node/QuestionAnswerListV2',
    form: {
      method: 'next',
      params: JSON.stringify({
        'url_token': params.token,
        'pagesize': params.pagesize,
        'offset': 10, // params.offset,
      })
    },

**Comment by shanelau** [comment]
@1736103466 谢谢提出，已经发布新版本解决。实际上，你可以通过传参数，覆盖代码里面写的`offset `。
