### ISSUE TITLE
建议使用ES6

### ISSUE THREAD

**Issue by sunchenguang** [shanelau/zhihu#27]
建议使用ES6优化代码，减少冗余，新版本的nodejs已经支持大部分ES6新特性了

**Comment by shanelau** [comment]
主要是问题，这个项目已经没在在我们的产品环境使用了。如果下次还用得上，我就会更新到 es6的写法了

**Comment by sunchenguang** [comment]
我可以写然后发个PR  -,-

**Comment by sunchenguang** [comment]
已合并
