### ISSUE TITLE
Unit test failed

### ISSUE THREAD

**Issue by snowmagic1** [shanelau/zhihu#9]
比如run这个
mocha test/User.test.js

===========================
 User
    #info
      1) should return user info object

  0 passing (2s)
  1 failing

  1) User #info should return user info object:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test

**Comment by iplus26** [comment]
已提交 PR
等@shanelau Merge

**Comment by shanelau** [comment]
已经修复 。知乎已经改成 https ，修复了所有接口
